name: internet_access_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  fluid_bottom_nav_bar: ^1.4.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/IAC_app_logo.png"

flutter:
  uses-material-design: true

  assets: 
    - assets/images/

  fonts: 
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
    - family: NotoSerif
      fonts: 
        - asset: fonts/NotoSerif-SemiBoldItalic.ttf